#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
#source ../reboot_kernel.exp

step "Starting test."

set timeout 8

set case_num 0

incr case_num

expect  -re $kernel_prompt
send -s "dhcpcd &\r"
while 1 {
expect {
-re "\[0-9]* dhcpcd.*$kernel_prompt" {
        case_pass $case_num
        send_log "\nGet ip address through dhcpcd.\n"
        break
}


timeout {
        case_fail $case_num
	exit
	}
}
}

incr case_num

send -s "ifconfig eth0\r" 
while 1 {
   sleep 3
   expect {
      -re "10.99.29..*$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}

incr case_num

send -s "ptpd -z linux_hw\r" 
while 1 {
   expect {
      -re "$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}

incr case_num

send -s "ps auxf\r" 
while 1 {
   expect {
      -re "ptpd.*linux_hw.*$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}
incr case_num

send -s "date \r" 
while 1 {
   expect {
      -re "$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}
incr case_num

send -s "date -s 2009.11.14-17:15:10\r" 
while 1 {
   expect {
      -re "$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 

