#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."

set timeout 8

set case_num 0

incr case_num

expect  -re $kernel_prompt
send -s "dmesg\r"
while 1 {
expect {
-re "input: ADXL34x accelerometer .*irq .*$kernel_prompt" {
        case_pass $case_num
        send_log "\nDetected device.\n"
        break
}


timeout {
        case_fail $case_num
	exit
	}
}
}

incr case_num

send -s "cat /sys/class/input/input1/name\r" 
while 1 {
   expect {
      -re "ADXL34x accelerometer.*$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}

incr case_num

send -s "cat /proc/interrupts\r" 
while 1 {
   expect {
      -re ".*$kernel_prompt" { 
                case_pass $case_num
         break
      }

      timeout {                           
                case_fail $case_num
      exit
         }
     }
}

send -s "event_test /dev/input/event1\r" 
while 1 {
   expect {
     -re "Input device name.*Testing" { 
         puts "\nPlease move the board...\n"	 
	 expect {
		-re "Event: time .* type .* code .* value " { 
                case_pass $case_num
			}
		
		timeout {                           
                case_fail $case_num
			exit
			}
		}
	 sleep 5
	 send -s "\003"
         expect -re $kernel_prompt
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}
send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 

