#!/usr/bin/expect

source ../kernel_config.exp

if { $argc < 2 } {
    puts "Please input: board_type, pm_state (standby or mem)"
    exit
}
set pm_state [lindex $argv 1]
set TITLE [title "$argv0"]
append TITLE " ($pm_state)"
set log_name power_adv7393_${pm_state}_test_log

log_file $log_name
send_user "Starting $argv0\n"
send_user "\n#### Power management state is $pm_state. ####\n"

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

set wait_time 15
set wakeup_fail 0
set wakeup_pattern "Syncing filesystems \.\.\. done\.\r\nFreezing user space processes \.\.\. \\\(elapsed.*seconds\\\) done\.\r\nFreezing remaining freezable tasks \.\.\. \\\(elapsed.*seconds\\\) done\.\r\nSuspending console\\\(s\\\).*Restarting tasks \.\.\. done.*$kernel_prompt"

proc standby_test_case1 {} {
    global case_num
    global kernel_prompt
    global wait_time
    global wakeup_fail
    global pm_state
    global wakeup_pattern

    set timeout [expr $wait_time + 10]
    incr case_num
    send "\nrtcwake -s $wait_time -m $pm_state\r"
    while 1 {
        expect {
            -re $wakeup_pattern {
                case_pass $case_num
                break
            }
            timeout {
                send_user "Test case 1: Wake up fail\n"
                incr wakeup_fail
                break
            }
        }
    }

    set timeout 5
    expect -re "Full\r\n|lpa 0x41E1\r\n"

    incr case_num
    set timeout 10
    send "video_test\r"
    while 1 {
        expect {
            -re "\r\n\[a-zA-Z0-9]" {
                case_fail $case_num
            }
            timeout {
                case_pass $case_num
                break
            }
        }
    }

    set timeout 5
    incr case_num
    send -s "\3"
    while 1 {
        expect {
            -re $kernel_prompt {
                case_pass $case_num
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }
}

proc standby_test_case2 {} {
    global case_num
    global kernel_prompt
    global wait_time
    global wakeup_fail
    global pm_state
    global wakeup_pattern

    set timeout [expr $wait_time + 10]
    incr case_num
    send "\nrtcwake -s $wait_time -m $pm_state\r"
    while 1 {
        expect {
            -re $wakeup_pattern {
                case_pass $case_num
                break
            }
            timeout {
                send_user "Test case 2: Wake up fail\n"
                incr wakeup_fail
                break
            }
        }
    }

    set timeout 5
    expect -re "Full\r\n|lpa 0x41E1\r\n"
}


step "Start testing"
set case_num 0
set Total_Count 5
sleep 5
send "\r"
expect -re $kernel_prompt

set timeout 20
incr case_num
send "modprobe bfin_adv7393fb\r"
while 1 {
    expect {
        -re "ADV7393 frame buffer device.*fb memory address : 0x\[0-9a-f]+.*$kernel_prompt" {
            break
        }
        timeout {
            send_user "Install module failed!\r"
            case_fail $case_num
        }
    }
}

send "lsmod\r"
while 1 {
    expect {
        -re "bfin_adv7393fb.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Install module failed!\r"
            case_fail $case_num
        }
    }
}

sleep 5

incr case_num
set timeout 10
send "video_test\r"
while 1 {
    expect {
        -re "\r\n\[a-zA-Z0-9]" {
            case_fail $case_num
        }
        timeout {
            case_pass $case_num
            break
        }
    }
}

set timeout 5
incr case_num
send -s "\3"
while 1 {
    expect {
         -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "cat /proc/mounts\r"
while 1 {
    expect {
        -re "sysfs /sys sysfs rw,nosuid,nodev,noexec.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "ls /sys/power\r"
while 1 {
    expect {
        -re "state.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

for {set count 1} {$count <= $Total_Count} {incr count} {
    standby_test_case1
    send_user "\nStandby test case 1 round $count pass\n\n"
}

set timeout 15
incr case_num
send "video_test&\r"
while 1 {
    expect {
        -re " \[0-9]+ video_test\r\n$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 5
for {set count 1} {$count <= $Total_Count} {incr count} {
    standby_test_case2
    send_user "\nStandby test case 2 round $count pass\n\n"
    sleep 5
}

set timeout 20
incr case_num
send "video_test_id=\`ps|awk \'\$5==\"video_test\" {print \$1}\'\`; kill \$video_test_id\r"
while 1 {
    expect {
        -re "(kill:|Usage:|\[eE]rror|\[fF]ail).*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            sleep 1
	    set timeout 5
            send "\r"
            expect -nocase -re "Done.*$kernel_prompt"
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 20
incr case_num
send "modprobe -r bfin_adv7393fb\r"
while 1 {
    expect {
        -re "(modprobe:|\[eE]rror|\[fF]ail).*$kernel_prompt" {
            send_user "Uninstall module failed!\r"
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Uninstall module failed!\r"
            case_fail $case_num
        }
    }
}

set timeout 20
incr case_num
send "lsmod\r"
while 1 {
    expect {
        -re "bfin_adv7393fb" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
if { $wakeup_fail == 0 } {
    send_user "Wake up pass\n"
    case_pass $case_num
} else {
    send_user "Wake up fail $wakeup_fail times\n"
    case_fail $case_num
}

all_pass
send_user "Ending $argv0\n"
log_file
