#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."
set timeout 8
set flag 0

send -s "modprobe bfin_can\r" 
while 1 {
   expect {
     -re "bfin_can device" {
         incr flag
	 puts "module insert success.\n"
         break
      }

      timeout { 
         puts "module probe failed.\n"                  
         break
         }
     }
}
expect  -re $kernel_prompt
send -s "lsmod\r" 
while 1 {
   expect {
      "bfin_can" {
         incr flag
	 puts "module ls success.\n"
         break
      }

      timeout { 
         puts "module ls failed.\n"                  
         break
         }
     }
}

for {set i 0} {$i < 2 } {incr i} {

if { $i == 0 } {
set can_freq 125000
} elseif { $i == 1 } {
set can_freq 1000000
}

expect  -re $kernel_prompt
send -s "ip link set can0 type can bitrate $can_freq\r" 
while 1 {
   expect {
     -re "bfin_can.*set" {
         incr flag
	 puts "set bitrate success.\n"
         break
      }

      timeout { 
         puts "set bitrate failed.\n"                  
         break
         
     }
}

expect  -re $kernel_prompt
send -s "ifconfig can0 up\r" 
while 1 {
   expect {
     -re "$kernel_prompt" {
         incr flag
	 puts "ifconfig success.\n"
         break
      }

      timeout { 
         puts "ifconfig failed.\n"                  
         break
         }
     }
}

send -s "candump can0\r" 
while 1 {
   expect {
     -re "can0 .*" { 
         incr flag
         send -s "\3"
         break
      }

      timeout {                           
         break
         }
     }
}

expect  -re $kernel_prompt
send -s "cansend can0 123#AABBCCDD\r" 
while 1 {
   sleep 3
   expect {
       -re $kernel_prompt { 
         incr flag
         break
      }

      timeout {                           
         break
         }
     }
}

expect  -re $kernel_prompt
send -s "cansend can0 12345678#1122334455667788\r" 
while 1 {
   sleep 3
   expect {
       -re $kernel_prompt { 
        incr flag
         break
      }

      timeout {                           
         break
         }
     }
}

expect  -re $kernel_prompt
send -s "cangen can0\r" 
while 1 {
   sleep 3
   expect {
       -re $kernel_prompt { 
        incr flag
         break
      }

      timeout {                           
         break
         }
     }
}

send -s "rmmod bfin_can\r"
while 1 {
   expect {
      "bfin_can" {
         puts "module ls failed.\n"
         break
      }

      timeout {
         incr flag
         puts "module ls success.\n"
         break
      }
     }
}
}

if { $flag == 6 *[ expr i + 1 ]  } {
   all_pass
} else {
   puts "canbus test failed.\n"
}


send_user "Ending $argv0\n"
log_file
 

